### ISSUE TITLE
Service.IsResolved(entrypoint) returns false for type:ExternalName 

### ISSUE THREAD

**Issue by taehwoi** [airshipit/kubernetes-entrypoint#1]
Hi,

Current code looks for endpoints with the same name to check if a service is resolved.

However, I believe that services created with ExternalNames should be considered as resolved, even without any endpoints.  

```yml
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ExternalName
  externalName: some.db.domain
```

```bash
dig +short mariadb.default.svc.cluster.local
some.db.domain.
.....
```
